server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.196.202.147:3306/people?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
#  application:
#    name: server-provider

mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mapper/*.xml

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      cache: false


#aliyun:
#  accessKeyID: LTAI4GATztwWQJWd6NGWvEBJ   #你的accessKeyID
#  accessKeySecret: v7iRG7K07X7b6lq3BOIB4w1bUzmsA7                #你的accessKeySecret
#  domain: dysmsapi.aliyuncs.com       #固定不变
#  regionId: cn-hangzhou               #固定不变
#  templateCode: SMS_201721401                  #你的模板code
#  signName: 人才生态圈